/*Reporte en ireport que muestre en un gráfico las unidades de
control desde la más usada a la menos usada*/

SELECT 
UC.UNID_CONTROL_DESCRIPCION AS UNIDAD_DE_CONTROL,
COUNT(REGISTRO.UNID_CONTROL_ID) AS VECES_UTILIZADA
FROM REGISTRO
INNER JOIN UNID_CONTROL UC ON REGISTRO.UNID_CONTROL_ID=UC.UNID_CONTROL_ID
GROUP BY UC.UNID_CONTROL_DESCRIPCION
ORDER BY COUNT(REGISTRO.UNID_CONTROL_ID) DESC;